### ISSUE TITLE
Cannot select modifier

### ISSUE THREAD

**Issue by auryn-macmillan** [gnosis/zodiac-pilot#20] opened 2022-08-09 03:03 UTC
**Describe the bug**
I tried setting up the pilot extension using a delay mod to connect to a pilot safe to a dao safe.
After connecting the pilot safe via wallet connect and entering the dao safe's address, I am unable to connect select the delay mod.

**To Reproduce**
1. Connect to the rinkeby testnet
2. deploy a safe to act as a DAO
3. deploy a safe to act as a pilot
4. use the zodiac safe app to deploy a delay mod on the DAO safe, then enable the pilot safe as a module on the delay mod
5. open an dapp
6. launch the zodiac pilot extension
7. use wallet connect to connect to the dapp from your pilot safe
8. past in the address of your DAO safe
9. try to select your mod. If the bug has been reproduced, the dropdown box will be empty and disabled.

**Expected behavior**
The dropdown box should be populated with any enabled modules on the DAO safe and I should be able to select one.

**Screenshots / logs**
![image](https://user-images.githubusercontent.com/8453294/183554035-5c5e75ed-5d20-4dda-89fc-0865d040708c.png)

**Comment by auryn-macmillan** [comment] 2022-08-09 03:24
Just tried this again on Gnosis Chain with the same result.

**Comment by jfschwarz** [comment] 2022-08-09 10:00
duplicate of #17. As a workaround, click the browser page reload button, modules should then show up

**Closed by jfschwarz** 2022-08-09 10:00 UTC
Labels: bug, duplicate
